name: Deploy to staging

on:
  pull_request:
    types:
      - closed

run-name: Deploy ${{ github.event.pull_request.title }} to staging

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          label=$(gh pr view ${{ github.event.number }} --json labels --jq '.labels[] | select(.name | startswith("service/")).name')
          tag="${label#service/}-staging"
          git tag -f "$tag"
          git push -f origin "$tag"
