name: Deploy to staging

on:
  pull_request:
    types:
      - closed

run-name: Deploy ${{ join(github.event.pull_request.labels.*.name) }} to staging

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
          fetch-depth: 0

      - name: Get service name
        id: get_service
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          label=$(gh pr view ${{ github.event.number }} --json labels --jq '.labels[] | select(.name | startswith("service/")).name')
          echo "name=${label#service/}" >> $GITHUB_OUTPUT

      - name: Get chart version
        id: get_chart
        run: |
          echo "version=$(yq '.version' charts/${{ steps.get_service.outputs.name }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: tag
        run: |
            service="${{ steps.get_service.outputs.name }}"
            chart="${{ steps.get_chart.outputs.version }}"
            chart_tag="${service}/${chart}"
            staging_tag="${service}/staging"
            git tag -f "$chart_tag"
            git tag -f "$staging_tag"
            git push -f --tags
