name: Promote to production

on:
  workflow_dispatch:
    inputs:
      service:
        description: Name of the service
        type: string
        required: true

run-name: Promote ${{inputs.service}} to production

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: tag
        run: |
          if git rev-parse "${{ inputs.service }}-production" > /dev/null 2>&1; then
            git tag -f "${{ inputs.service }}-production-rollback" "${{ inputs.service }}-production"
          fi
          git tag -f "${{ inputs.service }}-production" "${{ inputs.service }}-staging"
          git push -f --tags
