name: Rollback production service

on:
  workflow_dispatch:
    inputs:
      service:
        description: Name of the service
        type: string
        required: true

run-name: Rollback ${{inputs.service}} in production

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: tag
        env:
          GITHUB_ACTOR: antonosmond
          TOKEN: ${{ secrets.WORKFLOW_PAT }}
        run: |
          git remote set-url --push origin "https://$GITHUB_ACTOR:$TOKEN@github.com/$GITHUB_REPOSITORY"
          git tag -f "${{ inputs.service }}-production" "${{ inputs.service }}-production-rollback"
          git push -f --tags
