name: Rollback production service

on:
  workflow_dispatch:
    inputs:
      service:
        description: Name of the service
        type: string
        required: true
      chart-version:
        description: A specific chart version to rollback to
        type: string
        required: false

run-name: Rollback ${{inputs.service}} in production

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
          fetch-depth: 0

      - name: rollback
        if: inputs.chart-version == ''
        run: |
          git tag -f "${{ inputs.service }}/production" "${{ inputs.service }}/rollback"
          git push -f --tags

      - name: rollback to ${{ inputs.chart-version }}
        if: inputs.chart-version != ''
        run: |
          git checkout "${{ inputs.service }}/${{ inputs.chart-version }}"
          git tag -f "${{ inputs.service }}/production"
          git tag -f "${{ inputs.service }}/rollback"
          git push -f --tags
